apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sampleapp.fullname" . }}-secret-files
  labels:
{{ include "sampleapp.labels" . | indent 4 }}
type: Opaque
data:
{{/*
  Template tpl function does not work in range, the following link suggests
  a workaround https://github.com/helm/helm/issues/5979#issuecomment-518231758

  We set the .Values conext for the template renderer to provide the behavior
  as if it was an "in-chart" Helm template file.
*/}}
{{- $values := .Values -}}
{{- range $file, $content := .Values.confTemplates }}
  {{- $_ := set $ "key" ".Values" }}
  {{- $_ := set $ "value" $values }}
  {{ $file }}: {{ tpl $content $ | b64enc }}
{{- end }}
