---
apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  namespace: gocd
  labels:
    app: gocd-agent
spec:
  serviceAccountName: default
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v19.10.0
      volumeMounts:
      - name: kubeconf
        mountPath: /root/.kube
        readOnly: true
      securityContext:
        privileged: false
  volumes:
    - name: kubeconf
      secret:
        secretName: gocd-deployer-kubeconf
