---
apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  namespace: gocd
  labels:
    app: gocd-agent
spec:
  serviceAccountName: gocd-deployer
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: dysnix/gocd-agent-alpine:v19.10.0
