format_version: 3
pipelines:
  Features.Test:
    group: sampleapp
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/gocd-demo/node-bulletin-board.git
        shallow_clone: true
        auto_update: true
        branch: master
        destination: node-bulletin-board
      git1:
        git: https://github.com/dysnix/gocd-infra.git
        shallow_clone: true
        auto_update: true
        branch: master
        destination: gocd-infra
    stages:
    - id:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          Download.kubectl:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: /bin/bash
                arguments:
                - -c
                - |
                    pwd
                    echo -e "\n===>\n\n"
                    find /godata
                    echo -e "\n===>\n\n"
                    id
                    which sudo

            - exec:
                command: /bin/bash
                arguments:
                - -c
                - |
                  curl -Lo ./kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
                  chmod 755 ./kubectl
                  ./kubectl get pods -n gocd
                run_if: passed
